# Metadaten
name: Hello World

# Events
on: push

# Jobs
jobs:
    say-hello:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - run: node ./src/hello-world.js